[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  adafruit/Adafruit ADS1X15@^2.5.0

build_flags =
  -std=gnu++17
  -Wall
  -Wextra
  -D CORE_DEBUG_LEVEL=1
  -D LORAE5_REGION=\"US915\"
  -D LORAE5_APP_EUI=\"0000000000000000\"
  -D LORAE5_DEV_EUI=\"0000000000000000\"
  -D LORAE5_APP_KEY=\"00000000000000000000000000000000\"
  -D LORAE5_UPLINK_PORT=10
